### ISSUE TITLE
re-license under MPLv2

### ISSUE THREAD

**Issue by InfiniteLee** [NodeGuy/server-date#35]
I was wondering if you'd be open to re-licensing this project under a slightly more permissive license, like MPLv2? I'd like to contribute to a project that is under MIT using this, but I don't think its possible while this is LGPL.

**Comment by NodeGuy** [comment]
Yes, I'll do this soon.  Thanks for asking.

**Comment by InfiniteLee** [comment]
Yes, that would be perfectly fine. Thanks!

**Comment by banagale** [comment]
Created a PR to make this official.

**Comment by NodeGuy** [comment]
Done.
