### ISSUE TITLE
Client and server date/time does not sync up fast enough after changing the server's time.

### ISSUE THREAD

**Issue by SenseiDale** [NodeGuy/server-date#39]
I came into a situation that when i change the time of the server (let's say i changed it 5 hours earlier like from 22:30 to 17:30), the ServerDate() function does not get the updated server time up until the next day. Why is that? 

I tried to change ServerDate.synchronizationIntervalDelay into a sorter interval but to no avail.

**Comment by NodeGuy** [comment]
I don't know but I've rewritten the library and the new version won't have this problem.
