### ISSUE TITLE
Clearer explanation request

### ISSUE THREAD

**Issue by Chocolladin** [NodeGuy/server-date#43]
Dear, thanks for this lib.

Im not quiet sure to understand how it  works though. i cant find any remote server declared. from where / which server do you exactly fetch the date ? Do i have to set it up first ? 

Thanks in advance, 

Regards, 

Bertrand

**Comment by NodeGuy** [comment]
Hi Bertrand,

The date is fetched from the server that serves the library.  There is no need to set up a separate server.
